language: c
compiler:
  - gcc
#  - clang
before_install:
# http://about.travis-ci.org/docs/user/build-configuration/
  - git submodule update --init --recursive
  # http://about.travis-ci.org/docs/user/build-configuration/#Installing-Packages-Using-apt
  - sudo apt-get update -qq
  # and as suggested here https://github.com/glfw/glfw/issues/2#issuecomment-16725712
  - sudo apt-get install -qq x11proto-xf86vidmode-dev xorg-dev libglu1-mesa-dev
# http://about.travis-ci.org/docs/user/gui-and-headless-browsers/
####  - "export DISPLAY=:963.0"
#### if size start manually not via init script  - "sh -e /etc/init.d/xvfb start"
  - cd srcglfw3
  - cmake .
  - make
  - cd ..
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_963.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :963 -ac -screen 0 800x600x16"
  - sleep 3 # give xvfb some time to start
#install: cmake
before_script:
  - pwd
  - git status
  - find . -iname *.c
  - find . -iname *.a
  - pwd
  - cmake .
script:
  - make
  - "export DISPLAY=:963.0"
  - "DISPLAY=:963.0 ./test"
  - find . -iname *.a
