language: c
compiler:
  - gcc
#  - clang
before_install:
  # http://about.travis-ci.org/docs/user/build-configuration/#Installing-Packages-Using-apt
  - sudo apt-get update -qq
# http://about.travis-ci.org/docs/user/build-configuration/
  - git submodule update --init --recursive
  - git clone https://github.com/kaikuehne/mirror.git mirror
  - pwd
  #- sudo apt-get install #install libjpeg libjpeg-dev libfreetype6 libfreetype6-dev zlib1g-dev
  # installing requeriments PIL with jpeg support failed replace it with pillow... perhaps this also can work http://stackoverflow.com/a/14840374/682603 it is pillow? https://github.com/python-imaging/Pillow or something on the lines of http://askubuntu.com/questions/156484/how-do-i-install-python-imaging-library-pil?answertab=votes#tab-top
  # - sudo pip install pillow
  #- for pillow https://github.com/python-imaging/Pillow#linux lets see if PIL too travis Ubuntu 12.04 
  - sudo apt-get install libtiff4-dev libjpeg8-dev zlib1g-dev libfreetype6-dev
  - cd mirror
  - sudo pip install -r requirements.txt
  - cd ..
# NOTE: In OSX use export PKG_CONFIG_PATH=/usr/X11/lib/pkgconfig after install the others via brew
  # - sudo apt-get install libcairo2-dev fontconfig
  - npm install -g imagediff
  # and as suggested here https://github.com/glfw/glfw/issues/2#issuecomment-16725712
  - sudo apt-get install -qq x11proto-xf86vidmode-dev xorg-dev libglu1-mesa-dev
# http://about.travis-ci.org/docs/user/gui-and-headless-browsers/
####  - "export DISPLAY=:963.0"
#### if size start manually not via init script  - "sh -e /etc/init.d/xvfb start"
  - cd srcglfw3
  - cmake .
  - make
  - cd ..
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_963.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :963 -ac -screen 0 800x600x16"
  - sleep 3 # give xvfb some time to start
#install: cmake
before_script:
  - pwd
  - git status
  - find . -iname *.c
  - find . -iname *.a
  - pwd
  - cmake .
script:
  - make
  - "export DISPLAY=:963.0"
  - "DISPLAY=:963.0 ./test"
  - find . -iname *.a
  - mkdir img_out
  - imagediff -d img_orig/1_normal_a.jpg img_new/1_normal_b.jpg img_out/salida.jpg
  - imagediff -e img_orig/1_normal_a.jpg img_new/1_normal_b.jpg
  - python mirror/mirror.py img_orig/1_normal_a.jpg img_new/1_normal_b.jpg 
